/**
 * The scanned bodies a figure can be drawn with.
 *
 * Every body type comes in each of these. All but one are generated by the
 * same MakeHuman pipeline (`scripts/models/`) from the same rig and the same
 * mesh topology, so a model is purely a matter of how the figure looks: the
 * face and the body shape the MakeHuman ethnic and age targets give it, and
 * the skin photograph made for them. None of it reaches the collision field.
 * The skeleton, and so stature, proportions, the bust and every contact the
 * solver finds, is the body type's whatever the model, and the mesh is
 * retargeted onto it the way the default one always was. The one place the two
 * have to agree is the chest, because the field's bust is fitted to the
 * default female's painted areola and `featureRelief` moves the skin onto it;
 * so the bodies whose own breasts sat elsewhere were made with MakeHuman's
 * breast-position modifiers set to put the areola back (see
 * scripts/models/bodies.json), and on the rest pose every one is now within
 * 3 mm of the field's.
 *
 * The one that is not, `fine`, is a denser surface - Meta's MHR, five times the
 * triangles - fitted onto the default MakeHuman body it `standsFor`
 * (`scripts/models/make-fine-bodies.mjs`). It keeps that body's skeleton, its
 * eyes, its skin weights, its hair and the heights its clothes are cut at, and
 * wears its skin photograph, so it is the same figure drawn finer.
 *
 * `suffix` names the files in assets/models: `realistic-<type><suffix>.glb`,
 * and `skin-<type><suffix>.png` beside it - except that the neutral bodies
 * wear the female skins, which is what MakeHuman's gender-0.5 body is made
 * with, and a body that stands for another wears that one's.
 */
export const BODY_MODELS = {
  asian: { label: "East Asian, about 22", suffix: "" },
  european: { label: "European, about 22", suffix: "-european" },
  african: { label: "African, about 22", suffix: "-african" },
  mature: { label: "East Asian, about 50", suffix: "-mature" },
  fine: { label: "East Asian, about 22, finer", suffix: "-fine", standsFor: "asian" },
};
export const BODY_MODEL_NAMES = Object.keys(BODY_MODELS);
export const DEFAULT_BODY_MODEL = "asian";

/** A model name the files exist for; anything else is the default. */
export const bodyModel = (model) => (Object.hasOwn(BODY_MODELS, model) ? model : DEFAULT_BODY_MODEL);

/**
 * The stems of the files one body is drawn from, `female-european` and so on:
 * the mesh is `realistic-<mesh>.glb` and the atlas `skin-<atlas>.png`.
 */
export function modelFiles(bodyType, model) {
  const type = ["female", "male"].includes(bodyType) ? bodyType : "neutral";
  const { suffix, standsFor } = BODY_MODELS[bodyModel(model)];
  const skin = standsFor ? BODY_MODELS[standsFor].suffix : suffix;
  return { mesh: `${type}${suffix}`, atlas: `${type === "neutral" ? "female" : type}${skin}` };
}
