/**
 * The scanned bodies a figure can be drawn with.
 *
 * Every body type comes in each of these, all generated by the same MakeHuman
 * pipeline (`scripts/models/`) from the same rig and the same mesh topology, so
 * a model is purely a matter of how the figure looks: the face and the body
 * shape the MakeHuman ethnic and age targets give it, and the skin photograph
 * made for them. None of it reaches the collision field. The skeleton, and so
 * stature, proportions, the bust and every contact the solver finds, is the
 * body type's whatever the model, and the mesh is retargeted onto it the way
 * the default one always was. The one place the two have to agree is the
 * chest, because the field's bust is fitted to the default female's painted
 * areola and `featureRelief` moves the skin onto it; so the bodies whose own
 * breasts sat elsewhere were made with MakeHuman's breast-position modifiers
 * set to put the areola back (see scripts/models/bodies.json), and on the rest
 * pose every one is now within about 2 mm of the field's.
 *
 * `suffix` names the files in assets/models: `realistic-<type><suffix>.glb`,
 * and `skin-<type><suffix>.png` beside it - except that the neutral bodies
 * wear the female skins, which is what MakeHuman's gender-0.5 body is made
 * with.
 */
export const BODY_MODELS = {
  asian: { label: "East Asian, about 22", suffix: "" },
  european: { label: "European, about 22", suffix: "-european" },
  african: { label: "African, about 22", suffix: "-african" },
  mature: { label: "East Asian, about 50", suffix: "-mature" },
};
export const BODY_MODEL_NAMES = Object.keys(BODY_MODELS);
export const DEFAULT_BODY_MODEL = "asian";

/** A model name the files exist for; anything else is the default. */
export const bodyModel = (model) => (Object.hasOwn(BODY_MODELS, model) ? model : DEFAULT_BODY_MODEL);

/**
 * The stems of the files one body is drawn from, `female-european` and so on:
 * the mesh is `realistic-<mesh>.glb` and the atlas `skin-<atlas>.png`.
 */
export function modelFiles(bodyType, model) {
  const type = ["female", "male"].includes(bodyType) ? bodyType : "neutral";
  const { suffix } = BODY_MODELS[bodyModel(model)];
  return { mesh: `${type}${suffix}`, atlas: `${type === "neutral" ? "female" : type}${suffix}` };
}
